updated update_lambda func with better opts and simpler method for updating lambda which doesn't require refreshingin the console

diff --git a/bin/update_lambda b/bin/update_lambda
--- a/bin/update_lambda
+++ b/bin/update_lambda
@@ -1,33 +1,60 @@
 #!/bin/bash
 
-config_file=".lambda-config"
-if [[ $# -eq 0 && -f $config_file ]] ; then
-    bucket_name=`head -n 1 $config_file | tail -1`
-    read -a files <<< `head -n 2 $config_file | tail -1`
+config=.lambda-config
+default_region=us-east-1
+usage="\nusage: update-lambda [-n <name>] [-r <region>] [<files>...]\n"
+
+while getopts ':n:r:' opt ; do
+    case $opt in
+        n) name=$OPTARG ;;
+        r) region=$OPTARG ;;
+    esac
+done
+shift $(( OPTIND -1 ))
+
+if [ -z "$region" ] ; then
+    if [ -f "$config/region" ] ; then
+        region=`cat $config/region`
+    else
+        printf "No region provided or configured, using default region: $default_region\n"
+        region=$default_region
+    fi
 else
-    bucket_name=$1
-    files="${@:2}"
-    if [ -z "$bucket_name" ] ; then
-        printf "No bucket name given.\nusage: update-lambda [<bucket_name>] [<files>...]\n"
+    echo "$region" > "$config/region"
+fi
+if [ -z "$name" ] ; then
+    if [ -f "$config/name" ] ; then
+        name=`cat $config/name`
+    else
+        printf "No name provided or configured.$usage"
         exit 1
     fi
-    if [ ${#files[@]} -lt 1 ] ; then
-        printf "No files provided.\nusage: update-lambda [<bucket_name>] [<files>...]\n"
+else
+    if ! aws lambda get-function --function-name $name --region $region &>/dev/null ; then
+        printf "Could not find function named $name in $region.\n"
         exit 1
     fi
+    echo "$name" > "$config/name"
+fi
+if [ $# -gt 0 ] ; then
+    files=$@
     for file in $files ; do
         if [ ! -f $file ] ; then
             printf "$file doesn't exist.\n"
             exit 1
         fi
     done
+    echo "${files[*]}" > "$config/files"
+else
+    if [ -f "$config/files" ] ; then
+        read -a files <<< `cat $config/files`
+    else
+        printf "No files provided or configured.$usage"
+    fi
 fi
-echo "$bucket_name\n${files[@]}" > $config_file
+
 npm prune --production
-zip lambda $files
+zip lambda ${files[@]}
 zip -r lambda node_modules
-if ! aws s3 ls s3://$bucket_name &>/dev/null ; then
-    aws s3 mb s3://$bucket_name
-fi
-aws s3api put-object --bucket $bucket_name --key lambda.zip --body lambda.zip
+aws lambda update-function-code --function-name $name --zip-file fileb://lambda.zip --region $region
 npm install
